using NutriForge.Application.DietGen;
using NutriForge.Application.Planning;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace NutriForge.Api.Pdf;

/// <summary>
/// Renders a diet plan + its consolidated shopping list as a printable meal-prep PDF, modeled on a
/// classic batch-cook sheet: per-person/day meals by day, plus a days×people consolidated buy-list.
/// </summary>
public static class MealPlanPdf
{
    public static byte[] Render(DietPlanDto plan, ShoppingListDto shopping)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentNullException.ThrowIfNull(shopping);

        var eaters = Math.Max(1, plan.Eaters);            // headcount, for labels
        var portion = Math.Max(1, plan.PortionMultiplier); // Σ portion factors, for cook quantities
        var days = plan.Slots.Select(s => s.Day).DefaultIfEmpty(0).Max();
        var people = eaters == 1 ? "person" : "people";

        return Document.Create(doc =>
        {
            doc.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(36);
                page.DefaultTextStyle(t => t.FontSize(10).FontColor(Colors.Grey.Darken4));

                page.Header().Column(col =>
                {
                    col.Item().Text("NutriForge — Meal Prep Plan").FontSize(18).Bold();
                    col.Item().Text(text =>
                    {
                        text.Span($"{days} day{(days == 1 ? "" : "s")} × {eaters} {people} = {days * eaters} person-days");
                        text.Span($"   ·   per person/day ~{Math.Round(plan.AchievedKcal)} kcal (target {Math.Round(plan.TargetKcal)})")
                            .FontColor(Colors.Grey.Medium);
                    });
                    col.Item().PaddingTop(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
                });

                page.Content().PaddingVertical(8).Column(col =>
                {
                    col.Spacing(12);

                    foreach (var day in plan.Slots.GroupBy(s => s.Day).OrderBy(g => g.Key))
                    {
                        col.Item().Column(dayCol =>
                        {
                            dayCol.Item().Text($"Day {day.Key}").Bold().FontSize(12).FontColor(Colors.Green.Darken2);
                            dayCol.Item().Table(table =>
                            {
                                table.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(70);  // meal
                                    c.RelativeColumn();     // recipe
                                    c.ConstantColumn(85);   // per person
                                    c.ConstantColumn(70);   // cook total
                                    c.ConstantColumn(60);   // kcal
                                });

                                // Slots arrive already ordered by meal (Breakfast→Snack); keep that order.
                                foreach (var slot in day)
                                {
                                    table.Cell().Text(slot.MealSlot).FontColor(Colors.Grey.Medium);
                                    table.Cell().Text(slot.RecipeName);
                                    table.Cell().AlignRight().Text($"{Math.Round(slot.Servings, 2)}×/person");
                                    table.Cell().AlignRight().Text(portion > 1 ? $"cook {Math.Round(slot.Servings * portion, 2)}" : "—")
                                        .FontColor(Colors.Grey.Medium);
                                    table.Cell().AlignRight().Text($"{Math.Round(slot.Kcal)} kcal");
                                }
                            });
                        });
                    }

                    col.Item().PaddingTop(6).Text("Shopping list").Bold().FontSize(13).FontColor(Colors.Green.Darken2);
                    col.Item().Text($"Totals for {days} day{(days == 1 ? "" : "s")} × {eaters} {people}.")
                        .FontColor(Colors.Grey.Medium);

                    foreach (var aisle in shopping.Aisles)
                    {
                        col.Item().PaddingTop(4).Text(aisle.Aisle).Bold();
                        foreach (var item in aisle.Items)
                        {
                            col.Item().Row(row =>
                            {
                                row.RelativeItem().Text(item.IngredientName + (item.PantryCovered ? " (in pantry)" : ""));
                                row.ConstantItem(80).AlignRight().Text($"{Math.Round(item.Grams, 1)} g");
                            });
                        }
                    }
                });

                page.Footer().AlignCenter().Text("Generated by NutriForge").FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();
    }
}
