// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriForge.Infrastructure.Persistence;

#nullable disable

namespace NutriForge.Infrastructure.Persistence.Migrations.App
{
    [DbContext(typeof(NutriForgeDbContext))]
    [Migration("20260623195047_AddAssistantSession")]
    partial class AddAssistantSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriForge.Domain.Assistant.AssistantSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("assistant_sessions", "app");
                });

            modelBuilder.Entity("NutriForge.Domain.Catalog.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Gtin");

                    b.ToTable("foods", "catalog");
                });

            modelBuilder.Entity("NutriForge.Domain.Catalog.Portion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<double>("Grams")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("portions", "catalog");
                });

            modelBuilder.Entity("NutriForge.Domain.Diary.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CarbG")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Grams")
                        .HasColumnType("double precision");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PortionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("diary_entries", "app");
                });

            modelBuilder.Entity("NutriForge.Domain.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<List<string>>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<double?>("BodyFatPct")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Dislikes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("MacroStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<List<string>>("PreferredDiets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", "app");
                });

            modelBuilder.Entity("NutriForge.Domain.Users.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CarbG")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("targets", "app");
                });

            modelBuilder.Entity("NutriForge.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OidcSubject")
                        .IsUnique();

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("NutriForge.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key", "UserId")
                        .IsUnique();

                    b.ToTable("idempotency", "app");
                });

            modelBuilder.Entity("NutriForge.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox", "app");
                });

            modelBuilder.Entity("NutriForge.Domain.Catalog.Food", b =>
                {
                    b.OwnsOne("NutriForge.Domain.Catalog.FoodSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("FoodId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_provider");

                            b1.Property<string>("ProviderId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_provider_id");

                            b1.HasKey("FoodId");

                            b1.HasIndex("Provider", "ProviderId")
                                .IsUnique();

                            b1.ToTable("foods", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("NutriForge.Domain.Catalog.NutrientProfile", "NutrientProfile", b1 =>
                        {
                            b1.Property<Guid>("FoodId")
                                .HasColumnType("uuid");

                            b1.Property<double>("CarbPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("carb_per_100g");

                            b1.Property<double>("FatPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("fat_per_100g");

                            b1.Property<double?>("FiberPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("fiber_per_100g");

                            b1.Property<double>("KcalPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("kcal_per_100g");

                            b1.Property<double>("ProteinPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("protein_per_100g");

                            b1.Property<double?>("SodiumMgPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("sodium_mg_per_100g");

                            b1.Property<double?>("SugarPer100g")
                                .HasColumnType("double precision")
                                .HasColumnName("sugar_per_100g");

                            b1.HasKey("FoodId");

                            b1.ToTable("foods", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.Navigation("NutrientProfile")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("NutriForge.Domain.Catalog.Portion", b =>
                {
                    b.HasOne("NutriForge.Domain.Catalog.Food", null)
                        .WithMany("Portions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriForge.Domain.Catalog.Food", b =>
                {
                    b.Navigation("Portions");
                });
#pragma warning restore 612, 618
        }
    }
}
